apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
data:
  postgresql.conf: |
    max_connections = 100   
    ssl = on
    ssl_cert_file = '/etc/db-server-certs/tls.crt'
    ssl_key_file = '/etc/db-server-certs/tls.key'
    ssl_ca_file = '/etc/db-ca-certs/bookinfo-db.svc.crt'
    shared_buffers = 128MB  
    dynamic_shared_memory_type = posix   
    logging_collector = on
    log_filename = 'postgresql-%a.log'
    log_truncate_on_rotation = on
    log_rotation_age = 1d
    log_rotation_size = 0
    log_timezone = 'Etc/UTC'
    datestyle = 'iso, mdy'
    timezone = 'Etc/UTC'
    lc_messages = 'en_US.utf8' 
    lc_monetary = 'en_US.utf8'                      
    lc_numeric = 'en_US.utf8'                       
    lc_time = 'en_US.utf8'                          
